
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: |
      - checkpoint_3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          sudo apt install pkg-config
          sudo apt-get install build-essential libgtk-3-dev
          cd game
          sudo ./build b
          cd b
      
      - name: Run Tests
        run: |
          mkdir errors
          for test in $(ls ../../test_commands)
          do
            cat "../../test_commands/"$test | simplegame 2>  "$test"_test_report.txt
            if [[ -s "$test"_test_report.txt ]]
            then
              mv "$test"_test_report.txt errors/"$test"_test_report.txt
            else
              rm "$test"_test_report.txt
            fi
          done
          
      # Runs a set of commands using the runners shell
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Canvas
          path: |
            ^errors
      
